config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

from fitgenius.core.views import HomeRedirectView

urlpatterns = [
    path('tz_detect/', include('tz_detect.urls')),
    path("", HomeRedirectView.as_view(), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    path('', include("fitgenius.core.urls", namespace='core')),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("fitgenius.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here

    path('', include("fitgenius.club.urls", namespace='club')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

fitgenius/club/urls.py
from django.urls import path

from .views import (
    CreateActionView, UpdateActionView, ListActionView, BudgetCreateView, BudgetUpdateView, BudgetListView,
    # ProductUpdateView, ProductListView, ProductCreateView, DeleteProductView,
    OfferCreateView, OfferUpdateView, OfferListView, DeleteActionView, DeleteBudgetView,
    DeleteOfferView, OfferedItemUpdateFormView, OfferedItemCreateFormView, OfferedItemView,
    DeleteOfferedItemView, OfferList, OfferPartialUpdateView, BudgetSalesView, SetWorkingHoursView, ReportView,
    ActionList, BudgetTableView, WorkingHoursListView, UpdateWorkingHourView, DeleteWorkingHoursView
)

app_name = "club"

urlpatterns = [
    path('action/add/', CreateActionView.as_view(), name='add-action'),
    path('action/update/<int:pk>/', UpdateActionView.as_view(), name='update-action'),
    path('action/delete/<int:pk>/', DeleteActionView.as_view(), name='delete-action'),
    path('actions/', ListActionView.as_view(), name='list-action'),
    path('action/partial/', ActionList.as_view(), name='partial-list-action'),

    path('budget/add/', BudgetCreateView.as_view(), name='add-budget'),
    path('budget/update/<int:pk>/', BudgetUpdateView.as_view(), name='update-budget'),
    path('budget/delete/<int:pk>/', DeleteBudgetView.as_view(), name='delete-budget'),
    path('budgets/', BudgetListView.as_view(), name='list-budget'),
    path('budgets/table/', BudgetTableView.as_view(), name='budget-table'),

    # path('product/add/', ProductCreateView.as_view(), name='add-product'),
    # path('product/update/<int:pk>/', ProductUpdateView.as_view(), name='update-product'),
    # path('product/delete/<int:pk>/', DeleteProductView.as_view(), name='delete-product'),
    # path('products/', ProductListView.as_view(), name='list-product'),

    path('offer/add/', OfferCreateView.as_view(), name='add-offer'),
    path('offer/update/<int:pk>/', OfferUpdateView.as_view(), name='update-offer'),
    path('offer/update/pairtial/<int:pk>/', OfferPartialUpdateView.as_view(), name='partial-update-offer'),
    path('offer/delete/<int:pk>/', DeleteOfferView.as_view(), name='delete-offer'),
    path('offers/', OfferListView.as_view(), name='list-offer'),
    path('offers/partial/', OfferList.as_view(), name='partial-list-offer'),

    path('htmx/offered_item-form/create/', OfferedItemCreateFormView.as_view(), name='create-offered_item-form'),
    path('htmx/offered_item-form/<int:pk>/', OfferedItemUpdateFormView.as_view(), name='offered_item-form'),
    path('htmx/offered_item-form/delete/<int:pk>/', DeleteOfferedItemView.as_view(), name='offered_item-delete'),
    path('offered-item/', OfferedItemView.as_view()),

    path('b-sales/', BudgetSalesView.as_view(), name='budget-sales'),

    path('set-working-hours/', SetWorkingHoursView.as_view(), name='set-working-hours'),
    path('working-hours/', WorkingHoursListView.as_view(), name='working-hours'),
    path('working-hours/update/<int:pk>/', UpdateWorkingHourView.as_view(), name='update-working-hours'),
    path('working-hours/delete/<int:pk>/', DeleteWorkingHoursView.as_view(), name='delete-working-hours'),

    path('report/', ReportView.as_view(), name='report')

]

fitgenius/core/urls.py
from django.urls import path
from django.views.generic import TemplateView

from fitgenius.core.views import DashboardView

app_name = "core"

urlpatterns = [
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('auth-logout/', TemplateView.as_view(template_name="account/logout-success.html"), name='pages-logout'),
]

fitgenius/users/urls.py
from django.urls import path

from fitgenius.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view, CreateUserView, UpdateUserView, ListUserView, DeleteUserView, UpdateProfileView
)

app_name = "users"
urlpatterns = [
    # path("~redirect/", view=user_redirect_view, name="redirect"),
    # path("~update/", view=user_update_view, name="update"),

    path('', ListUserView.as_view(), name="list-user"),
    path("add/", CreateUserView.as_view(), name="add-user"),
    path('<uuid:uuid>/update/', UpdateUserView.as_view(), name="update-user"),
    path('<uuid:uuid>/delete/', DeleteUserView.as_view(), name="delete-user"),
    path('', ListUserView.as_view(), name="list-user"),
    # path("<str:username>/", view=user_detail_view, name="detail"),
    path("profile/", view=user_detail_view, name="detail"),
    path("update-profile/", view=UpdateProfileView.as_view(), name="update-profile"),
]

fitgenius/club/models.py
import uuid
import datetime
import decimal

from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import OuterRef, F, Sum, Subquery, Count
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.template.defaultfilters import slugify

User = get_user_model()


class Club(models.Model):
    name = models.CharField(max_length=255)
    manager = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='clubs')
    timestamp = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)

    def __str__(self):
        return self.name

    def get_time_worked(self):
        # from fitgenius.club.models import WorkingHour
        users = self.user_set.all()
        time_worked = sum([user.get_time_worked() for user in users])

        if time_worked is None:
            return 0
        return time_worked

    def get_current_day_sales(self):
        users = self.user_set.all()
        sales = sum([user.get_current_day_sales() for user in users])

        return sales

    def get_current_month_sales(self):
        users = self.user_set.all()
        sales = sum([user.get_current_month_sales() for user in users])

        return sales

    def get_referrals(self, client_type=None):
        users = self.user_set.all()
        try:
            referrals = sum([user.get_referrals() for user in users])
            return referrals
        except TypeError:
            return 0

    def get_sales(self, client_type=None):
        users = self.user_set.all()

        if not client_type:
            return sum([user.get_sales() for user in users])

        return sum([user.get_sales(client_type=client_type) for user in users])

    def finalized_sales_on_ref(self):
        # from fitgenius.club.models import Offer
        offer_qs = self.offer_set.agent_sales(agent_uuid=self.uuid).filter(client_type=Offer.REFERRAL)

        sales = offer_qs.aggregate(sales=Sum('total_sales'))
        return sales['sales']

    def ref_sales_ratio(self, client_type=None):
        # TODO: Get clarification
        try:
            if client_type:
                return self.get_referrals(client_type=client_type)/self.get_sales(client_type=client_type)
            return self.get_referrals()/self.get_sales()
        except decimal.InvalidOperation:
            return 0

    def get_call_per_hour(self):
        # from fitgenius.club.models import Action
        no_calls = self.action_set.filter(action=Action.CALLS).count()
        if no_calls == 0:
            return 0
        return self.get_time_worked()/no_calls

    def get_number_of_sales(self, product_name='all', client_type=None, category=None):
        users = self.user_set.all()

        return sum([user.get_number_of_sales(product_name=product_name, client_type=client_type, category=category) for user in users])

    def get_number_prospect_sales(self):
        # from fitgenius.club.models import Offer
        return self.get_number_of_sales(client_type=Offer.NEW_CLIENT, category=Offer.PROSPECT)

    def get_number_comeback_sales(self):
        # from fitgenius.club.models import Offer
        return self.get_number_of_sales(client_type=Offer.NEW_CLIENT, category=Offer.COMEBACK)

    def get_number_prospect_finalized_sales(self):
        users = self.user_set.all()
        return sum([user.get_number_prospect_finalized_sales() for user in users])

    def get_number_prospect_nonfinalized_sales(self):
        users = self.user_set.all()
        return sum([user.get_number_prospect_nonfinalized_sales() for user in users])

    def get_percentage_prospect_finalized(self):
        try:
            return (self.get_number_prospect_finalized_sales() / self.get_number_prospect_sales()) * 100
        except ZeroDivisionError:
            return 0

    def get_number_comeback_finalized_sales(self):
        users = self.user_set.all()
        return sum([user.get_number_comeback_finalized_sales() for user in users])

    def get_percentage_total_finalized(self):
        """filtered by new client"""
        try:
            return (self.get_number_prospect_finalized_sales() + self.get_number_comeback_finalized_sales()) * 100 / (
                self.get_number_prospect_sales() + self.get_number_comeback_sales())
        except ZeroDivisionError:
            return 0

    def get_days_budget(self, date):
        return sum([agent.get_days_budget(date) for agent in self.user_set.all()])

    def get_budget_for_range(self, start_date, end_date=None):
        if end_date is None:
            end_date = start_date + datetime.timedelta(days=1)
        users = self.user_set.all()
        return sum([agent.get_budget_for_range(start_date, end_date) for agent in users])

    def get_workingdays_for_range(self, start_date, end_date=None):
        if end_date is None:
            end_date = start_date + datetime.timedelta(days=1)
        users = self.user_set.all()
        return sum([agent.get_workingdays_for_range(start_date, end_date) for agent in users])

    def get_days_worked(self, start_date, end_date=None):
        if end_date is None:
            end_date = start_date + datetime.timedelta(days=1)
        users = self.user_set.all()
        return sum([agent.get_days_worked(start_date, end_date) for agent in users])

    def get_budget_progress(self, start_date, end_date=None):
        if end_date is None:
            end_date = start_date + datetime.timedelta(days=1)
        users = self.user_set.all()
        return sum([agent.get_budget_progress(start_date, end_date) for agent in users])

    def get_current_sales(self, start_date, end_date=None):
        if end_date is None:
            end_date = start_date + datetime.timedelta(days=1)
        users = self.user_set.all()
        return sum([agent.get_current_sales(start_date, end_date) for agent in users])

    def get_trend(self, start_date, end_date=None):
        if end_date is None:
            end_date = start_date + datetime.timedelta(days=1)

        try:
            trend = ((decimal.Decimal(self.get_current_sales(start_date, end_date)) * 100) / decimal.Decimal(self.get_budget_progress(start_date,
                                                                                                 end_date))) - 100
            return trend
        except (ZeroDivisionError, decimal.InvalidOperation):
            return 0


class Product(models.Model):
    title = models.CharField(max_length=255)
    # value = models.DecimalField(max_digits=18, decimal_places=2)
    # club = models.ForeignKey(Club, on_delete=models.SET_NULL, null=True)
    slug = models.SlugField(null=False, unique=True)
    uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)

    def __str__(self):
        return f'{self.title}'

    def save(self, *args, **kwargs):  # new
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)


class Budget(models.Model):
    club = models.ForeignKey(Club, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=18, decimal_places=2)
    agent = models.ForeignKey(User, on_delete=models.CASCADE)
    month = models.DateField()
    working_days = models.PositiveIntegerField(help_text=_("Number of working days"), default=23)

    timestamp = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)

    class Meta:
        ordering = ['-month']
        unique_together = [
            ['agent', 'month']
        ]

    def __str__(self):
        return f'{self.agent.username} | {self.month} | {self.amount}'

    @property
    def get_daily_budget(self):
        return self.amount / self.working_days


class OfferedItemManager(models.Manager):
    def agent_offered_items(self, agent_uuid):
        return self.filter(offer__agent__uuid=agent_uuid)


class OfferedItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    offer = models.ForeignKey('Offer', on_delete=models.CASCADE, null=True)
    # quantity = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=18, decimal_places=2, default=0)
    number_of_months = models.PositiveIntegerField(null=True, blank=True)

    timestamp = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)

    objects = OfferedItemManager()

    def __str__(self):
        if self.number_of_months is not None:
            return f'{self.product} | {self.price} | {self.number_of_months} months'
        return f'{self.product} | {self.price}'


class OfferManager(models.Manager):

    def agent_sales(self, agent_uuid):
        offered_items_qs = OfferedItem.objects.filter(offer=OuterRef('pk')).annotate(
            total_price=F('price')
        ).values('offer')

        oi_sum = offered_items_qs.annotate(oi_sum=Sum('total_price')).values('oi_sum')

        offer_qs = self.filter(agent__uuid=agent_uuid).annotate(
            total_sales=Subquery(oi_sum), no_product=Count('offereditem')
        )
        return offer_qs


class Offer(models.Model):
    NEW_CLIENT = 'new client'
    ACTIVE_CLIENT = 'active client'
    EX_CLIENT = 'ex-client'
    LEAD = 'lead'
    REFERRAL = 'referral'
    GUEST = 'guest'
    CROSS_UPGRADE = 'cross upgrade'

    CLIENT_TYPES = (
        (NEW_CLIENT, NEW_CLIENT.title()),
        (ACTIVE_CLIENT, ACTIVE_CLIENT.title()),
        (EX_CLIENT, EX_CLIENT.title()),
        (LEAD, LEAD.title()),
        (REFERRAL, REFERRAL.title()),
        (GUEST, GUEST.title()),
        (CROSS_UPGRADE, 'cross & upgrade'.title()),
    )

    SPONTANEOUS = 'spontaneous'
    COMEBACK = 'comeback'

fitgenius/core/models.py
from django.db import models

# Create your models here.

fitgenius/club/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.forms.widgets import TextInput
# from tempus_dominus.widgets import DatePicker

from .models import Action, Budget, Product, Offer, OfferedItem


User = get_user_model()


class DateInput(TextInput):
    input_type = 'date'


class MonthInput(TextInput):
    input_type = 'month'


class ActionForm(forms.ModelForm):
    class Meta:
        model = Action
        fields = ['action', 'category', 'amount', 'date']
        widgets = {
            'date': DateInput()
        }


class OfferForm(forms.ModelForm):
    class Meta:
        model = Offer
        fields = ['client_type', 'meeting_type', 'category', 'date', 'accepted', 'referrals']
        widgets = {
            'date': DateInput()
        }


class BudgetForm(forms.ModelForm):
    # month = MonthField()
    class Meta:
        model = Budget
        fields = ['agent', 'amount', 'month', 'working_days']
        widgets = {
            'month': TextInput(attrs={
                'class': 'picker',
                'readonly': True
            })
        }

    def __init__(self, *args, **kwargs):
        request = kwargs.pop('request', None)

        super().__init__(*args, **kwargs)

        self.fields['agent'].queryset = User.objects.filter(club=request.user.club)

fitgenius/templates/club/partials/action-list.html
{% for action in object_list %}
  <tr>
    {% if not request.GET.dashboard %}
      <td>{{ action.agent.get_full_name_or_username }}</td>
    {% endif %}
    <td>{{ action.amount }}</td>
    <td>{{ action.time_spent }}</td>
    <td>{{ action.get_category_display }}</td>
    <td>{{ action.get_action_display }}</td>
    <td>{{ action.date }}</td>
    <td>
      <button class="btn btn-outline-warning waves-effect waves-light" id="edit-{{ action.id }}"
      ><i class="bx bx-edit-alt"></i>
      </button>
      <button type="button" class="btn btn-outline-danger waves-effect waves-light" data-bs-toggle="modal"
              data-bs-target="#delete-action-{{ action.id }}"><i class="bx bx-trash-alt"></i>
      </button>
    </td>

  </tr>
{% endfor %}

fitgenius/templates/club/partials/offer-form.html
{% load static %}
{% load crispy_forms_tags %}


<div class="modal-content">
  <div class="modal-header">
    <h5 class="modal-title" id="offerAddModal">Offer</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
  </div>
  <div id="edit-offer-{{ object.id }}-body" class="modal-body">
    <form id="edit-offer-form-{{ object.id }}" hx-post="{% url 'club:update-offer' object.id %}">

      {% csrf_token %}
      {{ form|crispy }}

    </form>
    <div class="d-flex justify-content-end mb-3 mt-2">
      <button class="btn btn-outline-primary " hx-get="{% url 'club:create-offered_item-form' %}?of={{ object.id }}" hx-swap="beforeend" hx-target="#items-forms">Add product
      </button>
    </div>
    {% for item in object.offereditem_set.all %}
      <li class="d-none" hx-get="{% url 'club:offered_item-form' item.id %}" hx-trigger="load" hx-swap="beforeend" hx-target="#items-forms">x{{ item.quantity }} <b>{{ item.product.title }}</b> {{ item.number_of_months }} months</li>
    {% endfor %}
    <div id="items-forms"></div>

  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary waves-effect" data-bs-dismiss="modal">Close</button>
    <button form="edit-offer-form-{{ object.id }}" class="btn btn-primary waves-effect waves-light">
      Save changes
    </button>
  </div>
</div><!-- /.modal-content -->

fitgenius/templates/club/partials/offer-list.html
{% for offer in object_list %}
  <tr>
    <td>{{ forloop.counter }}</td>
    {% if not request.GET.dashboard %}
      <td>{{ offer.agent }}</td>
    {% endif %}
    <td>
      <ul>
        {% for item in offer.offereditem_set.all %}
          <li>
            <b>{{ item.product.title }}</b>
            {% if item.number_of_months %}
              {{ item.number_of_months }} month(s)
            {% endif %}
            {{ item.price }} €
          </li>
        {% endfor %}
      </ul>
    </td>
    <td>{{ offer.get_client_type_display }}</td>
    <td>{{ offer.get_meeting_type_display }}</td>
    <td>{{ offer.get_category_display }}</td>
    <td>{{ offer.accepted | yesno:"Yes,No" }}</td>
    <td>{{ offer.referrals }}</td>
    <td>{{ offer.date }}</td>

    <td>
      <div class="d-flex gap-3">
        <a href="javascript:void(0);" title="Delete" data-bs-toggle="modal" data-bs-target="#delete-offer-{{ offer.id }}" class="text-danger"><i class="mdi mdi-delete font-size-18"></i></a>
        <a href="javascript:void(0);" title="Edit" hx-target="#dialog" hx-get="{% url 'club:partial-update-offer' offer.id %}" class="text-success"><i class="mdi mdi-pencil font-size-18"></i></a>

      </div>
    </td>

  </tr>
{% endfor %}

fitgenius/templates/club/partials/offered_item-form.html
{% load crispy_forms_tags %}
<div id="offered-item-form-{{ object.id }}" hx-target="this" hx-swap="outerHTML">
  <form method="post">
    {% if messages %}
      <ul class="messages">
        {% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
      </ul>
    {% endif %}
    {% csrf_token %}

    <div class="row">
      <div class="form-group col-md-4 mb-0">
        {{ form.product|as_crispy_field }}
      </div>
      <div class="form-group col-md-4 mb-0">
        {{ form.price|as_crispy_field }}
      </div>
      <div class="form-group col-md-4 mb-0">
        {{ form.number_of_months|as_crispy_field }}
      </div>
    </div>
    {% if object %}
      <div class="d-flex justify-content-end mb-3">
        <button class="col-md-6 btn btn-outline-secondary" hx-post="{% url 'club:offered_item-form' object.id %}">Update</button>
        <button class="col-md-6 btn btn-outline-danger" hx-post="{% url 'club:offered_item-delete' object.id %}">Delete</button>
      </div>

    {% else %}
      <div class="d-flex justify-content-end mb-3">
        <button class="col-md-6 btn btn-outline-primary" hx-post="{% url 'club:create-offered_item-form' %}?of={{ offer_item_id }}">Submit</button>
        <button class="col-md-6 btn btn-outline-warning" type="button" onclick="removeForm('offered-item-form-{{ object.id }}')">remove</button>
      </div>

    {% endif %}

  </form>
</div>

fitgenius/templates/club/partials/working-hour-form.html
<div class="modal fade" id="workingHourModal" data-bs-backdrop="static" tabindex="-1"
     aria-labelledby="workingHourModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header border-bottom-0">
        {% comment %}
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        {% endcomment %}
      </div>
      <div class="modal-body">
        <div class="text-center mb-4">
          <div class="avatar-md mx-auto mb-4">
            <div class="avatar-title bg-light rounded-circle text-primary h1">
              <i class="mdi mdi-timetable"></i>
            </div>
          </div>
          <div class="row justify-content-center">
            <div class="col-xl-10">
              <h4 class="text-primary">Working Hours</h4>
              <p class="text-muted font-size-14 mb-4">
                Set the number of hours you will work today.
              </p>

              <form method="post" action="{% url 'club:set-working-hours' %}" class="input-group bg-light rounded">
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ request.path }}">
                <input type="number" name="hours" step="1" min="0" class="form-control bg-transparent border-0"
                       placeholder="No. of hours" aria-label="Recipient's username"
                       aria-describedby="button-addon2"/>

                <button class="btn btn-primary" type="submit" id="button-addon2">
                  <i class="bx bxs-paper-plane"></i>
                </button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  let HAS_WORKING_HOURS = {{ has_working_hours|yesno:"true,false" }};
  const myModal = new bootstrap.Modal(document.getElementById("workingHourModal"))

  if (!HAS_WORKING_HOURS) {
    myModal.show()
  };
</script>