config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

from fitgenius.core.views import HomeRedirectView

urlpatterns = [
    path('tz_detect/', include('tz_detect.urls')),
    path("", HomeRedirectView.as_view(), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    path('', include("fitgenius.core.urls", namespace='core')),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("fitgenius.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here

    path('', include("fitgenius.club.urls", namespace='club')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

fitgenius/club/urls.py
from django.urls import path

from .views import (
    CreateActionView, UpdateActionView, ListActionView, BudgetCreateView, BudgetUpdateView, BudgetListView,
    # ProductUpdateView, ProductListView, ProductCreateView, DeleteProductView,
    OfferCreateView, OfferUpdateView, OfferListView, DeleteActionView, DeleteBudgetView,
    DeleteOfferView, OfferedItemUpdateFormView, OfferedItemCreateFormView, OfferedItemView,
    DeleteOfferedItemView, OfferList, OfferPartialUpdateView, BudgetSalesView, SetWorkingHoursView, ReportView,
    ActionList, BudgetTableView, WorkingHoursListView, UpdateWorkingHourView, DeleteWorkingHoursView
)

app_name = "club"

urlpatterns = [
    path('action/add/', CreateActionView.as_view(), name='add-action'),
    path('action/update/<int:pk>/', UpdateActionView.as_view(), name='update-action'),
    path('action/delete/<int:pk>/', DeleteActionView.as_view(), name='delete-action'),
    path('actions/', ListActionView.as_view(), name='list-action'),
    path('action/partial/', ActionList.as_view(), name='partial-list-action'),

    path('budget/add/', BudgetCreateView.as_view(), name='add-budget'),
    path('budget/update/<int:pk>/', BudgetUpdateView.as_view(), name='update-budget'),
    path('budget/delete/<int:pk>/', DeleteBudgetView.as_view(), name='delete-budget'),
    path('budgets/', BudgetListView.as_view(), name='list-budget'),
    path('budgets/table/', BudgetTableView.as_view(), name='budget-table'),

    # path('product/add/', ProductCreateView.as_view(), name='add-product'),
    # path('product/update/<int:pk>/', ProductUpdateView.as_view(), name='update-product'),
    # path('product/delete/<int:pk>/', DeleteProductView.as_view(), name='delete-product'),
    # path('products/', ProductListView.as_view(), name='list-product'),

    path('offer/add/', OfferCreateView.as_view(), name='add-offer'),
    path('offer/update/<int:pk>/', OfferUpdateView.as_view(), name='update-offer'),
    path('offer/update/pairtial/<int:pk>/', OfferPartialUpdateView.as_view(), name='partial-update-offer'),
    path('offer/delete/<int:pk>/', DeleteOfferView.as_view(), name='delete-offer'),
    path('offers/', OfferListView.as_view(), name='list-offer'),
    path('offers/partial/', OfferList.as_view(), name='partial-list-offer'),

    path('htmx/offered_item-form/create/', OfferedItemCreateFormView.as_view(), name='create-offered_item-form'),
    path('htmx/offered_item-form/<int:pk>/', OfferedItemUpdateFormView.as_view(), name='offered_item-form'),
    path('htmx/offered_item-form/delete/<int:pk>/', DeleteOfferedItemView.as_view(), name='offered_item-delete'),
    path('offered-item/', OfferedItemView.as_view()),

    path('b-sales/', BudgetSalesView.as_view(), name='budget-sales'),

    path('set-working-hours/', SetWorkingHoursView.as_view(), name='set-working-hours'),
    path('working-hours/', WorkingHoursListView.as_view(), name='working-hours'),
    path('working-hours/update/<int:pk>/', UpdateWorkingHourView.as_view(), name='update-working-hours'),
    path('working-hours/delete/<int:pk>/', DeleteWorkingHoursView.as_view(), name='delete-working-hours'),

    path('report/', ReportView.as_view(), name='report')

]

fitgenius/core/urls.py
from django.urls import path
from django.views.generic import TemplateView

from fitgenius.core.views import DashboardView

app_name = "core"

urlpatterns = [
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('auth-logout/', TemplateView.as_view(template_name="account/logout-success.html"), name='pages-logout'),
]

fitgenius/users/urls.py
from django.urls import path

from fitgenius.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view, CreateUserView, UpdateUserView, ListUserView, DeleteUserView, UpdateProfileView
)

app_name = "users"
urlpatterns = [
    # path("~redirect/", view=user_redirect_view, name="redirect"),
    # path("~update/", view=user_update_view, name="update"),

    path('', ListUserView.as_view(), name="list-user"),
    path("add/", CreateUserView.as_view(), name="add-user"),
    path('<uuid:uuid>/update/', UpdateUserView.as_view(), name="update-user"),
    path('<uuid:uuid>/delete/', DeleteUserView.as_view(), name="delete-user"),
    path('', ListUserView.as_view(), name="list-user"),
    # path("<str:username>/", view=user_detail_view, name="detail"),
    path("profile/", view=user_detail_view, name="detail"),
    path("update-profile/", view=UpdateProfileView.as_view(), name="update-profile"),
]

fitgenius/core/models.py
from django.db import models

# Create your models here.

fitgenius/club/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.forms.widgets import TextInput
# from tempus_dominus.widgets import DatePicker

from .models import Action, Budget, Product, Offer, OfferedItem


User = get_user_model()


class DateInput(TextInput):
    input_type = 'date'


class MonthInput(TextInput):
    input_type = 'month'


class ActionForm(forms.ModelForm):
    class Meta:
        model = Action
        fields = ['action', 'category', 'amount', 'date']
        widgets = {
            'date': DateInput()
        }


class OfferForm(forms.ModelForm):
    class Meta:
        model = Offer
        fields = ['client_type', 'meeting_type', 'category', 'date', 'accepted', 'referrals']
        widgets = {
            'date': DateInput()
        }


class BudgetForm(forms.ModelForm):
    # month = MonthField()
    class Meta:
        model = Budget
        fields = ['agent', 'amount', 'month', 'working_days']
        widgets = {
            'month': TextInput(attrs={
                'class': 'picker',
                'readonly': True
            })
        }

    def __init__(self, *args, **kwargs):
        request = kwargs.pop('request', None)

        super().__init__(*args, **kwargs)

        self.fields['agent'].queryset = User.objects.filter(club=request.user.club)

fitgenius/club/views.py
import datetime

from allauth.account.views import SignupView
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum, OuterRef, F, Subquery
from django.forms.models import inlineformset_factory
from django.http import HttpResponseRedirect
from django.http.response import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic.base import TemplateView, View
from django.views.generic.edit import CreateView, UpdateView, BaseCreateView, DeleteView, FormView
from django.views.generic.list import ListView
from guardian.mixins import PermissionListMixin, PermissionRequiredMixin

from .forms import ActionForm, OfferForm, BudgetForm
from .models import Action, Budget, Product, Offer, OfferedItem, WorkingHour
from .utils import month_sale_vs_budget, generate_report, export_file, generate_actions_report, generate_budget_table
from ..users.forms import UserSignupForm
from ..utils.utils import PortalRestrictionMixin, AjaxTemplateMixin

User = get_user_model()


class CreateActionView(LoginRequiredMixin, CreateView):
    model = Action
    template_name = 'club/actions-form.html'
    # fields = ['action', 'category', 'amount', 'date']
    form_class = ActionForm
    success_url = reverse_lazy('club:list-action')

    def form_valid(self, form, *args, **kwargs):
        # form = super(CreateActionView, self).form_valid(*args, **kwargs)
        form.instance.agent = self.request.user
        form.instance.club = self.request.user.club
        return super().form_valid(form, *args, **kwargs)


class UpdateActionView(LoginRequiredMixin, PermissionRequiredMixin, AjaxTemplateMixin, UpdateView):
    model = Action
    template_name = 'club/actions-form.html'
    # fields = ['action', 'category', 'amount', 'date']
    form_class = ActionForm
    success_url = reverse_lazy('club:list-action')
    permission_required = ['club.access_action']
    raise_exception = True


class DeleteActionView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Action
    success_message = 'Successfully deleted'
    success_url = reverse_lazy('club:list-action')
    permission_required = ['club.access_action']
    raise_exception = True


class ListActionView(LoginRequiredMixin, PermissionListMixin, BaseCreateView, ListView):
    model = Action
    template_name = 'club/actions-list.html'
    # fields = ['action', 'category', 'amount', 'date']
    form_class = ActionForm
    success_url = reverse_lazy('club:list-action')
    permission_required = ['club.access_action']
    raise_exception = True
    # get_objects_for_user_extra_kwargs = {'use_groups': False}

    def form_valid(self, form, *args, **kwargs):
        # form = super(CreateActionView, self).form_valid(*args, **kwargs)
        form.instance.agent = self.request.user
        form.instance.club = self.request.user.club
        return super().form_valid(form, *args, **kwargs)


class ActionList(ListView):
    model = Action
    template_name = 'club/partials/action-list.html'
    permission_required = ['club.access_action']
    raise_exception = True

    def get_queryset(self):
        queryset = super().get_queryset()

        day = self.request.GET.get('d')
        month = self.request.GET.get('m')
        year = self.request.GET.get('y')
        if not all([day, month, year]):
            return queryset

        return queryset.filter(agent=self.request.user).filter(date__day=day, date__month=month, date__year=year)


class BudgetCreateView(LoginRequiredMixin, CreateView):
    model = Budget
    template_name = 'club/budget-form.html'
    # fields = ['agent', 'amount', 'month', 'working_days']
    form_class = BudgetForm
    success_url = reverse_lazy('club:list-budget')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

    def form_valid(self, form, *args, **kwargs):

        form.instance.club = form.instance.agent.club
        return super().form_valid(form, *args, **kwargs)


class BudgetUpdateView(LoginRequiredMixin, AjaxTemplateMixin, UpdateView):
    model = Budget
    template_name = 'club/budget-form.html'
    # fields = ['agent', 'amount', 'month', 'working_days']
    form_class = BudgetForm
    success_url = reverse_lazy('club:list-budget')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs


class BudgetSalesView(LoginRequiredMixin, View):
    # TODO: Restrict to only club manager
    def get(self, request, *args, **kwargs):
        month = request.GET.get('month')
        year = request.GET.get('year')
        day = request.GET.get('day')
        # agent = request.GET.get('agent')

        club = request.user.club
        data = []

        for agent in club.user_set.filter(user_type=User.AGENT):
            sales, budget = month_sale_vs_budget(agent.uuid, year, month)
            data.append({
                'sales': sales,
                'username': agent.username,
                'budget': budget,
                'name': agent.get_full_name()
            })

        # print(request.user, data, 'USER')

        return JsonResponse(data, safe=False)


class BudgetTableView(LoginRequiredMixin, PortalRestrictionMixin, ListView):
    model = Budget
    template_name = 'club/budget-table.html'

    def get_queryset(self):
        return Budget.objects.filter(club=self.request.user.club)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context.update({
            'budget_df': generate_budget_table(self.get_queryset(), self.request.user.club)
        })
        return context


class BudgetListView(LoginRequiredMixin, PortalRestrictionMixin, BaseCreateView, ListView):
    model = Budget
    template_name = 'club/budget-list.html'
    # fields = ['agent', 'amount', 'month', 'working_days']
    form_class = BudgetForm
    success_url = reverse_lazy('club:list-budget')

    def get_queryset(self):
        return Budget.objects.filter(club=self.request.user.club)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

    def form_valid(self, form, *args, **kwargs):
        # form = super(CreateActionView, self).form_valid(*args, **kwargs)
        form.instance.club = form.instance.agent.club
        return super().form_valid(form, *args, **kwargs)


class DeleteBudgetView(LoginRequiredMixin, DeleteView):
    model = Budget
    success_message = 'Successfully deleted'
    success_url = reverse_lazy('club:list-budget')

"""
class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    template_name = 'club/product-form.html'
    fields = ['title', 'value']
    success_url = reverse_lazy('club:list-product')

    def form_valid(self, form, *args, **kwargs):
        # form = super(CreateActionView, self).form_valid(*args, **kwargs)
        form.instance.club = self.request.user.club
        return super().form_valid(form, *args, **kwargs)


class ProductUpdateView(LoginRequiredMixin, AjaxTemplateMixin, UpdateView):
    model = Product
    template_name = 'club/product-form.html'
    fields = ['title', 'value']
    success_url = reverse_lazy('club:list-product')


class ProductListView(LoginRequiredMixin, PortalRestrictionMixin, BaseCreateView, ListView):
    model = Product
    template_name = 'club/product-list.html'
    fields = ['title', 'value']
    success_url = reverse_lazy('club:list-product')

    def form_valid(self, form, *args, **kwargs):
        # form = super(CreateActionView, self).form_valid(*args, **kwargs)
        form.instance.club = self.request.user.club
        return super().form_valid(form, *args, **kwargs)


class DeleteProductView(LoginRequiredMixin, DeleteView):
    model = Product
    success_message = 'Successfully deleted'
    success_url = reverse_lazy('club:list-product')
"""

OfferedItemFormset = inlineformset_factory(
    Offer, OfferedItem, fields=('product', 'price', 'number_of_months')
)


class OfferItemCreateView(CreateView):
    template_name = 'club/offer_item-form.html'
    fields = ['product', 'price', 'number_of_months']
    success_url = reverse_lazy('')


class OfferCreateView(LoginRequiredMixin, CreateView):
    model = Offer
    template_name = 'club/offer-form.html'
    # fields = ['agent', 'meeting_type', 'category', 'date', 'accepted', 'referrals']
    form_class = OfferForm
    success_url = reverse_lazy('club:list-offer')

    def get_initial(self):
        initial = super().get_initial()
        initial.update({
            'client_type': self.request.GET.get('client_type', default=None)
        })

    def get(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        offered_item_form = OfferedItemFormset()

        return self.render_to_response(
            self.get_context_data(
                form=form, offered_item_form=offered_item_form
            )
        )

    def post(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        offered_item_form = OfferedItemFormset(self.request.POST)

        if form.is_valid() and offered_item_form.is_valid():
            return self.form_valid(form, offered_item_form)
        else:
            return self.form_invalid(form, offered_item_form)

    def form_valid(self, form, offered_item_form):

        form.instance.agent = self.request.user
        self.object = form.save()
        offered_item_form.instance = self.object
        offered_item_form.save()
        return HttpResponseRedirect(self.get_success_url())

fitgenius/templates/users/update_profile-form.html
{% load crispy_forms_tags %}
<div class="modal-content">
  <div class="modal-header">
    <h5 class="modal-title" id="myModalLabel"></h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
  </div>
  <div class="modal-body">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title mb-4">Personal Information</h4>
        <div class="avatar-md profile-user-wid mb-4 mx-auto">
                <img src="{{user.get_img_url}}" alt="" class="img-thumbnail rounded-circle">
              </div>


        <form method="post" action="{% url 'users:update-profile' %}" enctype="multipart/form-data">
          {% csrf_token %}
          {{ form|crispy }}
          <button class="btn btn-primary">Submit</button>
        </form>
      </div>
    </div>
  </div>
</div>

fitgenius/templates/users/user-form.html
{% extends "partials/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Update user{% endblock %}

{% block contents %}
  <div class="row">
    <div class="col-xl-6">
      <div class="card">
        <div class="card-body">


          <form class="form-horizontal" method="post" action="{% url 'users:add-user' %}">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="control-group">
              <div class="controls">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock contents %}

fitgenius/templates/users/user-form_inner.html
{% load static %}
{% load crispy_forms_tags %}

<form id="edit-usr-form-{{ object.id }}" method="post" action="{% url 'users:update-user' object.uuid %}">
  {% csrf_token %}
  {{ form|crispy }}
</form>

fitgenius/templates/users/user-list.html
{% extends 'partials/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}{{ user.club.name }}'s users{% endblock title %}
{% block extra_css %}
  <!-- DataTables -->
  <link href="{% static 'libs/datatables.net-bs4/css/dataTables.bootstrap4.min.css' %}" rel="stylesheet"
        type="text/css"/>
  <link href="{% static 'libs/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css' %}" rel="stylesheet"
        type="text/css"/>

  <!-- Responsive datatable examples -->
  <link href="{% static 'libs/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css' %}" rel="stylesheet"
        type="text/css"/>
{% endblock %}
{% block contents %}
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">

          <h4 class="card-title mb-4">
            Users
            <button type="button" class="btn btn-primary waves-effect waves-light float-end" data-bs-toggle="modal"
                    data-bs-target="#addUserModal">Add
            </button>
          </h4>

          <div id="addUserModal" class="modal fade" tabindex="-1" aria-labelledby="userAddModal" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="userAddModal">Add User</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  <form id="add-user-form" method="post" action="{% url 'users:add-user' %}">
                    {% csrf_token %}
                    {{ form|crispy }}
                  </form>

                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary waves-effect" data-bs-dismiss="modal">Close</button>
                  <button form="add-user-form" class="btn btn-primary waves-effect waves-light">Save changes</button>
                </div>
              </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
          </div><!-- /.modal -->

          <!--<p class="card-title-desc">DataTables has most features enabled by
            default, so all you need to do to use it with your own tables is to call
            the construction function: <code>$().DataTable();</code>.
          </p>-->


          <table id="datatable" class="table table-bordered dt-responsive  nowrap w-100">
            <thead>
            <tr>
              <th>Username</th>
              <th>First Name</th>
              <th>Last Name</th>
              <th>Email</th>
              <th>Active</th>

              <th></th>

            </tr>
            </thead>


            <tbody>
            {% for usr in object_list %}
              <tr>
                <td>{{ usr.username }}</td>
                <td>{{ usr.first_name }}</td>
                <td>{{ usr.last_name }}</td>
                <td>{{ usr.email }}</td>
                <td>{{ usr.is_active|yesno:"Yes,No" }}</td>

                <td>
                  <button class="btn btn-outline-warning waves-effect waves-light" id="edit-{{ usr.id }}"
                     ><i class="bx bx-edit-alt"></i>
                  </button>
                  <button type="button" class="btn btn-outline-danger waves-effect waves-light" data-bs-toggle="modal"
                          data-bs-target="#delete-usr-{{ usr.id }}"><i class="bx bx-trash-alt"></i>
                  </button>
                </td>

              </tr>
            {% endfor %}

            </tbody>
          </table>
          {% for usr in object_list %}
            <div id="edit-usr-{{ usr.id }}" class="modal fade" tabindex="-1" aria-labelledby="usrAddModal"
                 aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="usrAddModal">Update User</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div id="edit-usr-{{ usr.id }}-body" class="modal-body">
                    ...loading

                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary waves-effect" data-bs-dismiss="modal">Close</button>
                    <button form="edit-usr-form-{{ usr.id }}" class="btn btn-primary waves-effect waves-light">Save changes
                    </button>
                  </div>
                </div><!-- /.modal-content -->
              </div><!-- /.modal-dialog -->
            </div><!-- /.modal -->


            <div id="delete-usr-{{ usr.id }}" class="modal fade" tabindex="-1" aria-labelledby="usrAddModal"
                 aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="usrAddModal">Delete {{ usr.username }}</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                    <p>Are you sure you want to delete <strong>{{ usr.username }}</strong>?</p>
                    <form id="delete-usr-{{ usr.id }}-form" method="post"
                          action="{% url 'users:delete-user' usr.uuid %}">
                      {% csrf_token %}

                    </form>

                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary waves-effect" data-bs-dismiss="modal">Close</button>
                    <button form="delete-usr-{{ usr.id }}-form" class="btn btn-danger waves-effect waves-light">
                      Delete
                    </button>
                  </div>
                </div><!-- /.modal-content -->
              </div><!-- /.modal-dialog -->
            </div><!-- /.modal -->
          {% endfor %}

        </div>
      </div>
    </div> <!-- end col -->
  </div> <!-- end row -->
{% endblock %}


{% block extra_javascript %}
  <!-- Required datatable js -->
  <script src="{% static 'libs/datatables.net/js/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'libs/datatables.net-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
  <!-- Buttons examples -->
  <script src="{% static 'libs/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
  <script src="{% static 'libs/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js' %}"></script>
  <script src="{% static 'libs/jszip/dist/jszip.min.js' %}"></script>
  <script src="{% static 'libs/pdfmake/build/pdfmake.min.js' %}"></script>
  <script src="{% static 'libs/pdfmake/build/vfs_fonts.js' %}"></script>
  <script src="{% static 'libs/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
  <script src="{% static 'libs/datatables.net-buttons/js/buttons.print.min.js' %}"></script>
  <script src="{% static 'libs/datatables.net-buttons/js/buttons.colVis.min.js' %}"></script>

  <!-- Responsive examples -->
  <script src="{% static 'libs/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
  <script src="{% static 'libs/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js' %}"></script>

  <!-- Datatable init js -->
  <script src="{% static 'js/pages/datatables.init.js' %}"></script>
  <script>

    var formAjaxSubmit = function (form, modal) {
      $(form).submit(function (e) {
        e.preventDefault();
        $.ajax({
          type: $(this).attr('method'),
          url: $(this).attr('action'),
          data: $(this).serialize(),
          success: function (xhr, ajaxOptions, thrownError) {
            if ($(xhr).find('.has-error').length > 0) {
              $(modal).find('.modal-body').html(xhr);
              formAjaxSubmit(form, modal);
            } else {
              $(modal).modal('toggle');
            }
          },
          error: function (xhr, ajaxOptions, thrownError) {
            // handle response errors here
          }
        });
      });
    }

    {% for usr in object_list %}
      $('#edit-{{ usr.id }}').click(function () {
        $('#edit-usr-{{ usr.id }}-body').load('{% url 'users:update-user' usr.uuid %}', function () {
          $('#edit-usr-{{ usr.id }}').modal('show');
          //formAjaxSubmit('#edit-usr-{{ usr.id }}-body', '#edit-usr-{{ usr.id }}');
        });
      })
    {% endfor %}
  </script>
{% endblock %}

fitgenius/templates/users/user_detail.html
<div class="modal-content">
  <div class="modal-header">
    <h5 class="modal-title" id="myModalLabel"></h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
  </div>
  <div class="modal-body">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title mb-4">Personal Information</h4>
        <div class="avatar-md profile-user-wid mb-4 mx-auto">
                <img src="{{user.get_img_url}}" alt="" class="img-thumbnail rounded-circle">
              </div>


        <div class="table-responsive">
          <table class="table table-nowrap mb-0">
            <tbody>
            <tr>
              <th scope="row">username :</th>
              <td>{{ user.username }}</td>
            </tr>
            <tr>
              <th scope="row">Full Name :</th>
              <td>{{ user.get_full_name }}</td>
            </tr>

            <tr>
              <th scope="row">Email :</th>
              <td>{{ user.email }}</td>
            </tr>

            </tbody>
          </table>
          <a href="javascript: void(0);" hx-target="#dialog" hx-get="{% url 'users:update-profile' %}"
                     class="btn btn-primary waves-effect waves-light btn-sm float-end mt-2">Edit Profile <i
                    class="mdi mdi-pencil ms-1"></i></a>
        </div>
      </div>
    </div>
  </div>
</div>

fitgenius/templates/users/user_form.html
{% extends "partials/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Update user{% endblock %}

{% block contents %}
  <div class="row">
    <div class="col-xl-6">
      <div class="card">
        <div class="card-body">


          <form class="form-horizontal" method="post" action="{% url 'users:add-user' %}">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="control-group">
              <div class="controls">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock contents %}